version: '3.8'

services:
  nginx-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-server
    ports:
      - "7000:80"
    volumes:
      - nginx_logs:/var/log/nginx
    networks:
      - my_bridge_network

  nginx-supervisor:
    image: ubuntu:20.04
    container_name: nginx-supervisor
    networks:
      - my_bridge_network
    volumes:
      - nginx_logs:/servlog
      - ./superviser.sh:/usr/local/bin/superviser.sh  # monte le .sh
    entrypoint: ["/bin/bash", "-c", "/usr/local/bin/superviser.sh"]  # lance le script

  curl-client:
    image: curlimages/curl
    container_name: curl-client
    networks:
      - my_bridge_network
    entrypoint: ["curl", "http://nginx-server:80"]

volumes:
  nginx_logs:

networks:
  my_bridge_network:
    driver: bridge

